// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod league_toolkit {

#[allow(unused_imports, dead_code)]
pub mod io {

#[allow(unused_imports, dead_code)]
pub mod release_manifest_file {


// struct ReleaseManifestLookupBucket, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ReleaseManifestLookupBucket(pub [u8; 36]);
impl Default for ReleaseManifestLookupBucket { 
  fn default() -> Self { 
    Self([0; 36])
  }
}
impl ::core::fmt::Debug for ReleaseManifestLookupBucket {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("ReleaseManifestLookupBucket")
      .field("Base", &self.Base())
      .field("SlotOffsets", &self.SlotOffsets())
      .field("SlotSeeds", &self.SlotSeeds())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for ReleaseManifestLookupBucket {}
impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestLookupBucket {
  type Inner = &'a ReleaseManifestLookupBucket;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a ReleaseManifestLookupBucket>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a ReleaseManifestLookupBucket {
  type Inner = &'a ReleaseManifestLookupBucket;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<ReleaseManifestLookupBucket>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for ReleaseManifestLookupBucket {
    type Output = ReleaseManifestLookupBucket;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const ReleaseManifestLookupBucket as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> ::flatbuffers::Verifiable for ReleaseManifestLookupBucket {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> ReleaseManifestLookupBucket {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    Base: u32,
    SlotOffsets: &[u8; 16],
    SlotSeeds: &[u8; 16],
  ) -> Self {
    let mut s = Self([0; 36]);
    s.set_Base(Base);
    s.set_SlotOffsets(SlotOffsets);
    s.set_SlotSeeds(SlotSeeds);
    s
  }

  pub fn Base(&self) -> u32 {
    let mut mem = ::core::mem::MaybeUninit::<<u32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_Base(&mut self, x: u32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn SlotOffsets(&'a self) -> ::flatbuffers::Array<'a, u8, 16> {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    use ::flatbuffers::Follow;
    unsafe { ::flatbuffers::Array::follow(&self.0, 4) }
  }

  pub fn set_SlotOffsets(&mut self, items: &[u8; 16]) {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { ::flatbuffers::emplace_scalar_array(&mut self.0, 4, items) };
  }

  pub fn SlotSeeds(&'a self) -> ::flatbuffers::Array<'a, u8, 16> {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    use ::flatbuffers::Follow;
    unsafe { ::flatbuffers::Array::follow(&self.0, 20) }
  }

  pub fn set_SlotSeeds(&mut self, items: &[u8; 16]) {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { ::flatbuffers::emplace_scalar_array(&mut self.0, 20, items) };
  }

}

pub enum ReleaseManifestBundleChunkOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestBundleChunk<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestBundleChunk<'a> {
  type Inner = ReleaseManifestBundleChunk<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestBundleChunk<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_COMPRESSEDSIZE: ::flatbuffers::VOffsetT = 6;
  pub const VT_UNCOMPRESSEDSIZE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestBundleChunk { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestBundleChunkArgs
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestBundleChunk<'bldr>> {
    let mut builder = ReleaseManifestBundleChunkBuilder::new(_fbb);
    builder.add_ID(args.ID);
    builder.add_UncompressedSize(args.UncompressedSize);
    builder.add_CompressedSize(args.CompressedSize);
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestBundleChunk::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn CompressedSize(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ReleaseManifestBundleChunk::VT_COMPRESSEDSIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn UncompressedSize(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ReleaseManifestBundleChunk::VT_UNCOMPRESSEDSIZE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestBundleChunk<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ID", Self::VT_ID, false)?
     .visit_field::<u32>("CompressedSize", Self::VT_COMPRESSEDSIZE, false)?
     .visit_field::<u32>("UncompressedSize", Self::VT_UNCOMPRESSEDSIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestBundleChunkArgs {
    pub ID: u64,
    pub CompressedSize: u32,
    pub UncompressedSize: u32,
}
impl<'a> Default for ReleaseManifestBundleChunkArgs {
  #[inline]
  fn default() -> Self {
    ReleaseManifestBundleChunkArgs {
      ID: 0,
      CompressedSize: 0,
      UncompressedSize: 0,
    }
  }
}

pub struct ReleaseManifestBundleChunkBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestBundleChunkBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestBundleChunk::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_CompressedSize(&mut self, CompressedSize: u32) {
    self.fbb_.push_slot::<u32>(ReleaseManifestBundleChunk::VT_COMPRESSEDSIZE, CompressedSize, 0);
  }
  #[inline]
  pub fn add_UncompressedSize(&mut self, UncompressedSize: u32) {
    self.fbb_.push_slot::<u32>(ReleaseManifestBundleChunk::VT_UNCOMPRESSEDSIZE, UncompressedSize, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestBundleChunkBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestBundleChunkBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestBundleChunk<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestBundleChunk<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestBundleChunk");
      ds.field("ID", &self.ID());
      ds.field("CompressedSize", &self.CompressedSize());
      ds.field("UncompressedSize", &self.UncompressedSize());
      ds.finish()
  }
}
pub enum ReleaseManifestBundleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestBundle<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestBundle<'a> {
  type Inner = ReleaseManifestBundle<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestBundle<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_CHUNKS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestBundle { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestBundleArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestBundle<'bldr>> {
    let mut builder = ReleaseManifestBundleBuilder::new(_fbb);
    builder.add_ID(args.ID);
    if let Some(x) = args.Chunks { builder.add_Chunks(x); }
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestBundle::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Chunks(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk>>>>(ReleaseManifestBundle::VT_CHUNKS, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestBundle<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ID", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk>>>>("Chunks", Self::VT_CHUNKS, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestBundleArgs<'a> {
    pub ID: u64,
    pub Chunks: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk<'a>>>>>,
}
impl<'a> Default for ReleaseManifestBundleArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestBundleArgs {
      ID: 0,
      Chunks: None,
    }
  }
}

pub struct ReleaseManifestBundleBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestBundleBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestBundle::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_Chunks(&mut self, Chunks: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBundle::VT_CHUNKS, Chunks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestBundleBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestBundleBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestBundle<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestBundle<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestBundle");
      ds.field("ID", &self.ID());
      ds.field("Chunks", &self.Chunks());
      ds.finish()
  }
}
pub enum ReleaseManifestLanguageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestLanguage<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestLanguage<'a> {
  type Inner = ReleaseManifestLanguage<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestLanguage<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestLanguage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestLanguageArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestLanguage<'bldr>> {
    let mut builder = ReleaseManifestLanguageBuilder::new(_fbb);
    if let Some(x) = args.Name { builder.add_Name(x); }
    builder.add_ID(args.ID);
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestLanguage::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ReleaseManifestLanguage::VT_NAME, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestLanguage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("ID", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("Name", Self::VT_NAME, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestLanguageArgs<'a> {
    pub ID: u8,
    pub Name: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ReleaseManifestLanguageArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestLanguageArgs {
      ID: 0,
      Name: None,
    }
  }
}

pub struct ReleaseManifestLanguageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestLanguageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestLanguage::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_Name(&mut self, Name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestLanguage::VT_NAME, Name);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestLanguageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestLanguageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestLanguage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestLanguage<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestLanguage");
      ds.field("ID", &self.ID());
      ds.field("Name", &self.Name());
      ds.finish()
  }
}
pub enum ReleaseManifestFileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestFile<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestFile<'a> {
  type Inner = ReleaseManifestFile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestFile<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_DIRECTORYID: ::flatbuffers::VOffsetT = 6;
  pub const VT_SIZE: ::flatbuffers::VOffsetT = 8;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 10;
  pub const VT_TAGBITMASK: ::flatbuffers::VOffsetT = 12;
  pub const VT_UNKNOWN5: ::flatbuffers::VOffsetT = 14;
  pub const VT_UNKNOWN6: ::flatbuffers::VOffsetT = 16;
  pub const VT_CHUNKIDS: ::flatbuffers::VOffsetT = 18;
  pub const VT_UNKNOWN8: ::flatbuffers::VOffsetT = 20;
  pub const VT_LINK: ::flatbuffers::VOffsetT = 22;
  pub const VT_KEYID: ::flatbuffers::VOffsetT = 24;
  pub const VT_CHUNKINGPARAMETERSID: ::flatbuffers::VOffsetT = 26;
  pub const VT_PERMISSIONS: ::flatbuffers::VOffsetT = 28;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestFile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestFileArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestFile<'bldr>> {
    let mut builder = ReleaseManifestFileBuilder::new(_fbb);
    builder.add_TagBitmask(args.TagBitmask);
    builder.add_Size(args.Size);
    builder.add_DirectoryID(args.DirectoryID);
    builder.add_ID(args.ID);
    if let Some(x) = args.Link { builder.add_Link(x); }
    if let Some(x) = args.ChunkIDs { builder.add_ChunkIDs(x); }
    if let Some(x) = args.Name { builder.add_Name(x); }
    builder.add_ChunkingParametersID(args.ChunkingParametersID);
    builder.add_KeyID(args.KeyID);
    builder.add_Permissions(args.Permissions);
    builder.add_Unknown8(args.Unknown8);
    builder.add_Unknown6(args.Unknown6);
    builder.add_Unknown5(args.Unknown5);
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestFile::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn DirectoryID(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestFile::VT_DIRECTORYID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestFile::VT_SIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ReleaseManifestFile::VT_NAME, None)}
  }
  #[inline]
  pub fn TagBitmask(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestFile::VT_TAGBITMASK, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Unknown5(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestFile::VT_UNKNOWN5, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Unknown6(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestFile::VT_UNKNOWN6, Some(0)).unwrap()}
  }
  #[inline]
  pub fn ChunkIDs(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(ReleaseManifestFile::VT_CHUNKIDS, None)}
  }
  #[inline]
  pub fn Unknown8(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestFile::VT_UNKNOWN8, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Link(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ReleaseManifestFile::VT_LINK, None)}
  }
  #[inline]
  pub fn KeyID(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ReleaseManifestFile::VT_KEYID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn ChunkingParametersID(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ReleaseManifestFile::VT_CHUNKINGPARAMETERSID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Permissions(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestFile::VT_PERMISSIONS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestFile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ID", Self::VT_ID, false)?
     .visit_field::<u64>("DirectoryID", Self::VT_DIRECTORYID, false)?
     .visit_field::<u64>("Size", Self::VT_SIZE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("Name", Self::VT_NAME, false)?
     .visit_field::<u64>("TagBitmask", Self::VT_TAGBITMASK, false)?
     .visit_field::<u8>("Unknown5", Self::VT_UNKNOWN5, false)?
     .visit_field::<u8>("Unknown6", Self::VT_UNKNOWN6, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("ChunkIDs", Self::VT_CHUNKIDS, false)?
     .visit_field::<u8>("Unknown8", Self::VT_UNKNOWN8, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("Link", Self::VT_LINK, false)?
     .visit_field::<u16>("KeyID", Self::VT_KEYID, false)?
     .visit_field::<u16>("ChunkingParametersID", Self::VT_CHUNKINGPARAMETERSID, false)?
     .visit_field::<u8>("Permissions", Self::VT_PERMISSIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestFileArgs<'a> {
    pub ID: u64,
    pub DirectoryID: u64,
    pub Size: u64,
    pub Name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub TagBitmask: u64,
    pub Unknown5: u8,
    pub Unknown6: u8,
    pub ChunkIDs: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub Unknown8: u8,
    pub Link: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub KeyID: u16,
    pub ChunkingParametersID: u16,
    pub Permissions: u8,
}
impl<'a> Default for ReleaseManifestFileArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestFileArgs {
      ID: 0,
      DirectoryID: 0,
      Size: 0,
      Name: None,
      TagBitmask: 0,
      Unknown5: 0,
      Unknown6: 0,
      ChunkIDs: None,
      Unknown8: 0,
      Link: None,
      KeyID: 0,
      ChunkingParametersID: 0,
      Permissions: 0,
    }
  }
}

pub struct ReleaseManifestFileBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestFileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestFile::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_DirectoryID(&mut self, DirectoryID: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestFile::VT_DIRECTORYID, DirectoryID, 0);
  }
  #[inline]
  pub fn add_Size(&mut self, Size: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestFile::VT_SIZE, Size, 0);
  }
  #[inline]
  pub fn add_Name(&mut self, Name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestFile::VT_NAME, Name);
  }
  #[inline]
  pub fn add_TagBitmask(&mut self, TagBitmask: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestFile::VT_TAGBITMASK, TagBitmask, 0);
  }
  #[inline]
  pub fn add_Unknown5(&mut self, Unknown5: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestFile::VT_UNKNOWN5, Unknown5, 0);
  }
  #[inline]
  pub fn add_Unknown6(&mut self, Unknown6: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestFile::VT_UNKNOWN6, Unknown6, 0);
  }
  #[inline]
  pub fn add_ChunkIDs(&mut self, ChunkIDs: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestFile::VT_CHUNKIDS, ChunkIDs);
  }
  #[inline]
  pub fn add_Unknown8(&mut self, Unknown8: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestFile::VT_UNKNOWN8, Unknown8, 0);
  }
  #[inline]
  pub fn add_Link(&mut self, Link: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestFile::VT_LINK, Link);
  }
  #[inline]
  pub fn add_KeyID(&mut self, KeyID: u16) {
    self.fbb_.push_slot::<u16>(ReleaseManifestFile::VT_KEYID, KeyID, 0);
  }
  #[inline]
  pub fn add_ChunkingParametersID(&mut self, ChunkingParametersID: u16) {
    self.fbb_.push_slot::<u16>(ReleaseManifestFile::VT_CHUNKINGPARAMETERSID, ChunkingParametersID, 0);
  }
  #[inline]
  pub fn add_Permissions(&mut self, Permissions: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestFile::VT_PERMISSIONS, Permissions, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestFileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestFileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestFile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestFile<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestFile");
      ds.field("ID", &self.ID());
      ds.field("DirectoryID", &self.DirectoryID());
      ds.field("Size", &self.Size());
      ds.field("Name", &self.Name());
      ds.field("TagBitmask", &self.TagBitmask());
      ds.field("Unknown5", &self.Unknown5());
      ds.field("Unknown6", &self.Unknown6());
      ds.field("ChunkIDs", &self.ChunkIDs());
      ds.field("Unknown8", &self.Unknown8());
      ds.field("Link", &self.Link());
      ds.field("KeyID", &self.KeyID());
      ds.field("ChunkingParametersID", &self.ChunkingParametersID());
      ds.field("Permissions", &self.Permissions());
      ds.finish()
  }
}
pub enum ReleaseManifestDirectoryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestDirectory<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestDirectory<'a> {
  type Inner = ReleaseManifestDirectory<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestDirectory<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_PARENTID: ::flatbuffers::VOffsetT = 6;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestDirectory { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestDirectoryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestDirectory<'bldr>> {
    let mut builder = ReleaseManifestDirectoryBuilder::new(_fbb);
    builder.add_ParentID(args.ParentID);
    builder.add_ID(args.ID);
    if let Some(x) = args.Name { builder.add_Name(x); }
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestDirectory::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn ParentID(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ReleaseManifestDirectory::VT_PARENTID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ReleaseManifestDirectory::VT_NAME, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestDirectory<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ID", Self::VT_ID, false)?
     .visit_field::<u64>("ParentID", Self::VT_PARENTID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("Name", Self::VT_NAME, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestDirectoryArgs<'a> {
    pub ID: u64,
    pub ParentID: u64,
    pub Name: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ReleaseManifestDirectoryArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestDirectoryArgs {
      ID: 0,
      ParentID: 0,
      Name: None,
    }
  }
}

pub struct ReleaseManifestDirectoryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestDirectoryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestDirectory::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_ParentID(&mut self, ParentID: u64) {
    self.fbb_.push_slot::<u64>(ReleaseManifestDirectory::VT_PARENTID, ParentID, 0);
  }
  #[inline]
  pub fn add_Name(&mut self, Name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestDirectory::VT_NAME, Name);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestDirectoryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestDirectoryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestDirectory<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestDirectory<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestDirectory");
      ds.field("ID", &self.ID());
      ds.field("ParentID", &self.ParentID());
      ds.field("Name", &self.Name());
      ds.finish()
  }
}
pub enum ReleaseManifestEncryptionKeyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestEncryptionKey<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestEncryptionKey<'a> {
  type Inner = ReleaseManifestEncryptionKey<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestEncryptionKey<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestEncryptionKey { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestEncryptionKeyArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestEncryptionKey<'bldr>> {
    let mut builder = ReleaseManifestEncryptionKeyBuilder::new(_fbb);
    if let Some(x) = args.Key { builder.add_Key(x); }
    builder.add_ID(args.ID);
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ReleaseManifestEncryptionKey::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Key(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ReleaseManifestEncryptionKey::VT_KEY, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestEncryptionKey<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("ID", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("Key", Self::VT_KEY, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestEncryptionKeyArgs<'a> {
    pub ID: u16,
    pub Key: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ReleaseManifestEncryptionKeyArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestEncryptionKeyArgs {
      ID: 0,
      Key: None,
    }
  }
}

pub struct ReleaseManifestEncryptionKeyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestEncryptionKeyBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u16) {
    self.fbb_.push_slot::<u16>(ReleaseManifestEncryptionKey::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_Key(&mut self, Key: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestEncryptionKey::VT_KEY, Key);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestEncryptionKeyBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestEncryptionKeyBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestEncryptionKey<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestEncryptionKey<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestEncryptionKey");
      ds.field("ID", &self.ID());
      ds.field("Key", &self.Key());
      ds.finish()
  }
}
pub enum ReleaseManifestChunkingParameterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestChunkingParameter<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestChunkingParameter<'a> {
  type Inner = ReleaseManifestChunkingParameter<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestChunkingParameter<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 6;
  pub const VT_MINCHUNKSIZE: ::flatbuffers::VOffsetT = 8;
  pub const VT_TARGETCHUNKSIZE: ::flatbuffers::VOffsetT = 10;
  pub const VT_MAXCHUNKSIZE: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestChunkingParameter { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestChunkingParameterArgs
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestChunkingParameter<'bldr>> {
    let mut builder = ReleaseManifestChunkingParameterBuilder::new(_fbb);
    builder.add_MaxChunkSize(args.MaxChunkSize);
    builder.add_TargetChunkSize(args.TargetChunkSize);
    builder.add_MinChunkSize(args.MinChunkSize);
    builder.add_ID(args.ID);
    builder.add_Version(args.Version);
    builder.finish()
  }


  #[inline]
  pub fn ID(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ReleaseManifestChunkingParameter::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Version(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestChunkingParameter::VT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn MinChunkSize(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ReleaseManifestChunkingParameter::VT_MINCHUNKSIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn TargetChunkSize(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ReleaseManifestChunkingParameter::VT_TARGETCHUNKSIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn MaxChunkSize(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ReleaseManifestChunkingParameter::VT_MAXCHUNKSIZE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestChunkingParameter<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("ID", Self::VT_ID, false)?
     .visit_field::<u8>("Version", Self::VT_VERSION, false)?
     .visit_field::<u32>("MinChunkSize", Self::VT_MINCHUNKSIZE, false)?
     .visit_field::<u32>("TargetChunkSize", Self::VT_TARGETCHUNKSIZE, false)?
     .visit_field::<u32>("MaxChunkSize", Self::VT_MAXCHUNKSIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestChunkingParameterArgs {
    pub ID: u16,
    pub Version: u8,
    pub MinChunkSize: u32,
    pub TargetChunkSize: u32,
    pub MaxChunkSize: u32,
}
impl<'a> Default for ReleaseManifestChunkingParameterArgs {
  #[inline]
  fn default() -> Self {
    ReleaseManifestChunkingParameterArgs {
      ID: 0,
      Version: 0,
      MinChunkSize: 0,
      TargetChunkSize: 0,
      MaxChunkSize: 0,
    }
  }
}

pub struct ReleaseManifestChunkingParameterBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestChunkingParameterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ID(&mut self, ID: u16) {
    self.fbb_.push_slot::<u16>(ReleaseManifestChunkingParameter::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_Version(&mut self, Version: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestChunkingParameter::VT_VERSION, Version, 0);
  }
  #[inline]
  pub fn add_MinChunkSize(&mut self, MinChunkSize: u32) {
    self.fbb_.push_slot::<u32>(ReleaseManifestChunkingParameter::VT_MINCHUNKSIZE, MinChunkSize, 0);
  }
  #[inline]
  pub fn add_TargetChunkSize(&mut self, TargetChunkSize: u32) {
    self.fbb_.push_slot::<u32>(ReleaseManifestChunkingParameter::VT_TARGETCHUNKSIZE, TargetChunkSize, 0);
  }
  #[inline]
  pub fn add_MaxChunkSize(&mut self, MaxChunkSize: u32) {
    self.fbb_.push_slot::<u32>(ReleaseManifestChunkingParameter::VT_MAXCHUNKSIZE, MaxChunkSize, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestChunkingParameterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestChunkingParameterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestChunkingParameter<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestChunkingParameter<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestChunkingParameter");
      ds.field("ID", &self.ID());
      ds.field("Version", &self.Version());
      ds.field("MinChunkSize", &self.MinChunkSize());
      ds.field("TargetChunkSize", &self.TargetChunkSize());
      ds.field("MaxChunkSize", &self.MaxChunkSize());
      ds.finish()
  }
}
pub enum ReleaseManifestPackedIndexesOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestPackedIndexes<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestPackedIndexes<'a> {
  type Inner = ReleaseManifestPackedIndexes<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestPackedIndexes<'a> {
  pub const VT_COUNT: ::flatbuffers::VOffsetT = 4;
  pub const VT_BITWIDTH: ::flatbuffers::VOffsetT = 6;
  pub const VT_DATA: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestPackedIndexes { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestPackedIndexesArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'bldr>> {
    let mut builder = ReleaseManifestPackedIndexesBuilder::new(_fbb);
    if let Some(x) = args.Data { builder.add_Data(x); }
    builder.add_Count(args.Count);
    builder.add_BitWidth(args.BitWidth);
    builder.finish()
  }


  #[inline]
  pub fn Count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ReleaseManifestPackedIndexes::VT_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn BitWidth(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ReleaseManifestPackedIndexes::VT_BITWIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn Data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ReleaseManifestPackedIndexes::VT_DATA, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestPackedIndexes<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("Count", Self::VT_COUNT, false)?
     .visit_field::<u8>("BitWidth", Self::VT_BITWIDTH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("Data", Self::VT_DATA, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestPackedIndexesArgs<'a> {
    pub Count: u32,
    pub BitWidth: u8,
    pub Data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ReleaseManifestPackedIndexesArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestPackedIndexesArgs {
      Count: 0,
      BitWidth: 0,
      Data: None,
    }
  }
}

pub struct ReleaseManifestPackedIndexesBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestPackedIndexesBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_Count(&mut self, Count: u32) {
    self.fbb_.push_slot::<u32>(ReleaseManifestPackedIndexes::VT_COUNT, Count, 0);
  }
  #[inline]
  pub fn add_BitWidth(&mut self, BitWidth: u8) {
    self.fbb_.push_slot::<u8>(ReleaseManifestPackedIndexes::VT_BITWIDTH, BitWidth, 0);
  }
  #[inline]
  pub fn add_Data(&mut self, Data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestPackedIndexes::VT_DATA, Data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestPackedIndexesBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestPackedIndexesBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestPackedIndexes<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestPackedIndexes");
      ds.field("Count", &self.Count());
      ds.field("BitWidth", &self.BitWidth());
      ds.field("Data", &self.Data());
      ds.finish()
  }
}
pub enum ReleaseManifestLookupOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestLookup<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestLookup<'a> {
  type Inner = ReleaseManifestLookup<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestLookup<'a> {
  pub const VT_BUCKETS: ::flatbuffers::VOffsetT = 4;
  pub const VT_ENTRIES: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestLookup { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestLookupArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestLookup<'bldr>> {
    let mut builder = ReleaseManifestLookupBuilder::new(_fbb);
    if let Some(x) = args.Entries { builder.add_Entries(x); }
    if let Some(x) = args.Buckets { builder.add_Buckets(x); }
    builder.finish()
  }


  #[inline]
  pub fn Buckets(&self) -> Option<::flatbuffers::Vector<'a, ReleaseManifestLookupBucket>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ReleaseManifestLookupBucket>>>(ReleaseManifestLookup::VT_BUCKETS, None)}
  }
  #[inline]
  pub fn Entries(&self) -> Option<ReleaseManifestPackedIndexes<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestLookup::VT_ENTRIES, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestLookup<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ReleaseManifestLookupBucket>>>("Buckets", Self::VT_BUCKETS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>("Entries", Self::VT_ENTRIES, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestLookupArgs<'a> {
    pub Buckets: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ReleaseManifestLookupBucket>>>,
    pub Entries: Option<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'a>>>,
}
impl<'a> Default for ReleaseManifestLookupArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestLookupArgs {
      Buckets: None,
      Entries: None,
    }
  }
}

pub struct ReleaseManifestLookupBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestLookupBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_Buckets(&mut self, Buckets: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ReleaseManifestLookupBucket>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestLookup::VT_BUCKETS, Buckets);
  }
  #[inline]
  pub fn add_Entries(&mut self, Entries: ::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestLookup::VT_ENTRIES, Entries);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestLookupBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestLookupBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestLookup<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestLookup<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestLookup");
      ds.field("Buckets", &self.Buckets());
      ds.field("Entries", &self.Entries());
      ds.finish()
  }
}
pub enum ReleaseManifestChunkLookupOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestChunkLookup<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestChunkLookup<'a> {
  type Inner = ReleaseManifestChunkLookup<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestChunkLookup<'a> {
  pub const VT_LOOKUP: ::flatbuffers::VOffsetT = 4;
  pub const VT_BUNDLEINDEX: ::flatbuffers::VOffsetT = 6;
  pub const VT_CHUNKS: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestChunkLookup { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestChunkLookupArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestChunkLookup<'bldr>> {
    let mut builder = ReleaseManifestChunkLookupBuilder::new(_fbb);
    if let Some(x) = args.Chunks { builder.add_Chunks(x); }
    if let Some(x) = args.BundleIndex { builder.add_BundleIndex(x); }
    if let Some(x) = args.Lookup { builder.add_Lookup(x); }
    builder.finish()
  }


  #[inline]
  pub fn Lookup(&self) -> Option<ReleaseManifestLookup<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>(ReleaseManifestChunkLookup::VT_LOOKUP, None)}
  }
  #[inline]
  pub fn BundleIndex(&self) -> Option<ReleaseManifestChunkBundleIndex<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestChunkBundleIndex>>(ReleaseManifestChunkLookup::VT_BUNDLEINDEX, None)}
  }
  #[inline]
  pub fn Chunks(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk>>>>(ReleaseManifestChunkLookup::VT_CHUNKS, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestChunkLookup<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>("Lookup", Self::VT_LOOKUP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestChunkBundleIndex>>("BundleIndex", Self::VT_BUNDLEINDEX, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk>>>>("Chunks", Self::VT_CHUNKS, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestChunkLookupArgs<'a> {
    pub Lookup: Option<::flatbuffers::WIPOffset<ReleaseManifestLookup<'a>>>,
    pub BundleIndex: Option<::flatbuffers::WIPOffset<ReleaseManifestChunkBundleIndex<'a>>>,
    pub Chunks: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk<'a>>>>>,
}
impl<'a> Default for ReleaseManifestChunkLookupArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestChunkLookupArgs {
      Lookup: None,
      BundleIndex: None,
      Chunks: None,
    }
  }
}

pub struct ReleaseManifestChunkLookupBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestChunkLookupBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_Lookup(&mut self, Lookup: ::flatbuffers::WIPOffset<ReleaseManifestLookup<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestLookup>>(ReleaseManifestChunkLookup::VT_LOOKUP, Lookup);
  }
  #[inline]
  pub fn add_BundleIndex(&mut self, BundleIndex: ::flatbuffers::WIPOffset<ReleaseManifestChunkBundleIndex<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestChunkBundleIndex>>(ReleaseManifestChunkLookup::VT_BUNDLEINDEX, BundleIndex);
  }
  #[inline]
  pub fn add_Chunks(&mut self, Chunks: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestBundleChunk<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestChunkLookup::VT_CHUNKS, Chunks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestChunkLookupBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestChunkLookupBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestChunkLookup<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestChunkLookup<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestChunkLookup");
      ds.field("Lookup", &self.Lookup());
      ds.field("BundleIndex", &self.BundleIndex());
      ds.field("Chunks", &self.Chunks());
      ds.finish()
  }
}
pub enum ReleaseManifestChunkBundleIndexOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestChunkBundleIndex<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestChunkBundleIndex<'a> {
  type Inner = ReleaseManifestChunkBundleIndex<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestChunkBundleIndex<'a> {
  pub const VT_BLOCKBUNDLE: ::flatbuffers::VOffsetT = 4;
  pub const VT_BLOCKMASK: ::flatbuffers::VOffsetT = 6;
  pub const VT_MASKS: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestChunkBundleIndex { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestChunkBundleIndexArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestChunkBundleIndex<'bldr>> {
    let mut builder = ReleaseManifestChunkBundleIndexBuilder::new(_fbb);
    if let Some(x) = args.Masks { builder.add_Masks(x); }
    if let Some(x) = args.BlockMask { builder.add_BlockMask(x); }
    if let Some(x) = args.BlockBundle { builder.add_BlockBundle(x); }
    builder.finish()
  }


  #[inline]
  pub fn BlockBundle(&self) -> Option<ReleaseManifestPackedIndexes<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestChunkBundleIndex::VT_BLOCKBUNDLE, None)}
  }
  #[inline]
  pub fn BlockMask(&self) -> Option<ReleaseManifestPackedIndexes<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestChunkBundleIndex::VT_BLOCKMASK, None)}
  }
  #[inline]
  pub fn Masks(&self) -> Option<ReleaseManifestPackedIndexes<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestChunkBundleIndex::VT_MASKS, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestChunkBundleIndex<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>("BlockBundle", Self::VT_BLOCKBUNDLE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>("BlockMask", Self::VT_BLOCKMASK, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestPackedIndexes>>("Masks", Self::VT_MASKS, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestChunkBundleIndexArgs<'a> {
    pub BlockBundle: Option<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'a>>>,
    pub BlockMask: Option<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'a>>>,
    pub Masks: Option<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'a>>>,
}
impl<'a> Default for ReleaseManifestChunkBundleIndexArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestChunkBundleIndexArgs {
      BlockBundle: None,
      BlockMask: None,
      Masks: None,
    }
  }
}

pub struct ReleaseManifestChunkBundleIndexBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestChunkBundleIndexBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_BlockBundle(&mut self, BlockBundle: ::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestChunkBundleIndex::VT_BLOCKBUNDLE, BlockBundle);
  }
  #[inline]
  pub fn add_BlockMask(&mut self, BlockMask: ::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestChunkBundleIndex::VT_BLOCKMASK, BlockMask);
  }
  #[inline]
  pub fn add_Masks(&mut self, Masks: ::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestPackedIndexes>>(ReleaseManifestChunkBundleIndex::VT_MASKS, Masks);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestChunkBundleIndexBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestChunkBundleIndexBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestChunkBundleIndex<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestChunkBundleIndex<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestChunkBundleIndex");
      ds.field("BlockBundle", &self.BlockBundle());
      ds.field("BlockMask", &self.BlockMask());
      ds.field("Masks", &self.Masks());
      ds.finish()
  }
}
pub enum ReleaseManifestBodyOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReleaseManifestBody<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReleaseManifestBody<'a> {
  type Inner = ReleaseManifestBody<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReleaseManifestBody<'a> {
  pub const VT_BUNDLES: ::flatbuffers::VOffsetT = 4;
  pub const VT_LANGUAGES: ::flatbuffers::VOffsetT = 6;
  pub const VT_FILES: ::flatbuffers::VOffsetT = 8;
  pub const VT_DIRECTORIES: ::flatbuffers::VOffsetT = 10;
  pub const VT_ENCRYPTIONKEYS: ::flatbuffers::VOffsetT = 12;
  pub const VT_CHUNKINGPARAMETERS: ::flatbuffers::VOffsetT = 14;
  pub const VT_CHUNKLOOKUP: ::flatbuffers::VOffsetT = 16;
  pub const VT_BUNDLELOOKUP: ::flatbuffers::VOffsetT = 18;
  pub const VT_FILELOOKUP: ::flatbuffers::VOffsetT = 20;
  pub const VT_DIRECTORYLOOKUP: ::flatbuffers::VOffsetT = 22;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReleaseManifestBody { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReleaseManifestBodyArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReleaseManifestBody<'bldr>> {
    let mut builder = ReleaseManifestBodyBuilder::new(_fbb);
    if let Some(x) = args.DirectoryLookup { builder.add_DirectoryLookup(x); }
    if let Some(x) = args.FileLookup { builder.add_FileLookup(x); }
    if let Some(x) = args.BundleLookup { builder.add_BundleLookup(x); }
    if let Some(x) = args.ChunkLookup { builder.add_ChunkLookup(x); }
    if let Some(x) = args.ChunkingParameters { builder.add_ChunkingParameters(x); }
    if let Some(x) = args.EncryptionKeys { builder.add_EncryptionKeys(x); }
    if let Some(x) = args.Directories { builder.add_Directories(x); }
    if let Some(x) = args.Files { builder.add_Files(x); }
    if let Some(x) = args.Languages { builder.add_Languages(x); }
    if let Some(x) = args.Bundles { builder.add_Bundles(x); }
    builder.finish()
  }


  #[inline]
  pub fn Bundles(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundle<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundle>>>>(ReleaseManifestBody::VT_BUNDLES, None)}
  }
  #[inline]
  pub fn Languages(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestLanguage<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestLanguage>>>>(ReleaseManifestBody::VT_LANGUAGES, None)}
  }
  #[inline]
  pub fn Files(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestFile<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestFile>>>>(ReleaseManifestBody::VT_FILES, None)}
  }
  #[inline]
  pub fn Directories(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestDirectory<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestDirectory>>>>(ReleaseManifestBody::VT_DIRECTORIES, None)}
  }
  #[inline]
  pub fn EncryptionKeys(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestEncryptionKey<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestEncryptionKey>>>>(ReleaseManifestBody::VT_ENCRYPTIONKEYS, None)}
  }
  #[inline]
  pub fn ChunkingParameters(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestChunkingParameter<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestChunkingParameter>>>>(ReleaseManifestBody::VT_CHUNKINGPARAMETERS, None)}
  }
  #[inline]
  pub fn ChunkLookup(&self) -> Option<ReleaseManifestChunkLookup<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestChunkLookup>>(ReleaseManifestBody::VT_CHUNKLOOKUP, None)}
  }
  #[inline]
  pub fn BundleLookup(&self) -> Option<ReleaseManifestLookup<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>(ReleaseManifestBody::VT_BUNDLELOOKUP, None)}
  }
  #[inline]
  pub fn FileLookup(&self) -> Option<ReleaseManifestLookup<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>(ReleaseManifestBody::VT_FILELOOKUP, None)}
  }
  #[inline]
  pub fn DirectoryLookup(&self) -> Option<ReleaseManifestLookup<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>(ReleaseManifestBody::VT_DIRECTORYLOOKUP, None)}
  }
}

impl ::flatbuffers::Verifiable for ReleaseManifestBody<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundle>>>>("Bundles", Self::VT_BUNDLES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestLanguage>>>>("Languages", Self::VT_LANGUAGES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestFile>>>>("Files", Self::VT_FILES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestDirectory>>>>("Directories", Self::VT_DIRECTORIES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestEncryptionKey>>>>("EncryptionKeys", Self::VT_ENCRYPTIONKEYS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ReleaseManifestChunkingParameter>>>>("ChunkingParameters", Self::VT_CHUNKINGPARAMETERS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestChunkLookup>>("ChunkLookup", Self::VT_CHUNKLOOKUP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>("BundleLookup", Self::VT_BUNDLELOOKUP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>("FileLookup", Self::VT_FILELOOKUP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ReleaseManifestLookup>>("DirectoryLookup", Self::VT_DIRECTORYLOOKUP, false)?
     .finish();
    Ok(())
  }
}
pub struct ReleaseManifestBodyArgs<'a> {
    pub Bundles: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestBundle<'a>>>>>,
    pub Languages: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestLanguage<'a>>>>>,
    pub Files: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestFile<'a>>>>>,
    pub Directories: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestDirectory<'a>>>>>,
    pub EncryptionKeys: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestEncryptionKey<'a>>>>>,
    pub ChunkingParameters: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ReleaseManifestChunkingParameter<'a>>>>>,
    pub ChunkLookup: Option<::flatbuffers::WIPOffset<ReleaseManifestChunkLookup<'a>>>,
    pub BundleLookup: Option<::flatbuffers::WIPOffset<ReleaseManifestLookup<'a>>>,
    pub FileLookup: Option<::flatbuffers::WIPOffset<ReleaseManifestLookup<'a>>>,
    pub DirectoryLookup: Option<::flatbuffers::WIPOffset<ReleaseManifestLookup<'a>>>,
}
impl<'a> Default for ReleaseManifestBodyArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReleaseManifestBodyArgs {
      Bundles: None,
      Languages: None,
      Files: None,
      Directories: None,
      EncryptionKeys: None,
      ChunkingParameters: None,
      ChunkLookup: None,
      BundleLookup: None,
      FileLookup: None,
      DirectoryLookup: None,
    }
  }
}

pub struct ReleaseManifestBodyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReleaseManifestBodyBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_Bundles(&mut self, Bundles: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestBundle<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBody::VT_BUNDLES, Bundles);
  }
  #[inline]
  pub fn add_Languages(&mut self, Languages: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestLanguage<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBody::VT_LANGUAGES, Languages);
  }
  #[inline]
  pub fn add_Files(&mut self, Files: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestFile<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBody::VT_FILES, Files);
  }
  #[inline]
  pub fn add_Directories(&mut self, Directories: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestDirectory<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBody::VT_DIRECTORIES, Directories);
  }
  #[inline]
  pub fn add_EncryptionKeys(&mut self, EncryptionKeys: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestEncryptionKey<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBody::VT_ENCRYPTIONKEYS, EncryptionKeys);
  }
  #[inline]
  pub fn add_ChunkingParameters(&mut self, ChunkingParameters: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ReleaseManifestChunkingParameter<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ReleaseManifestBody::VT_CHUNKINGPARAMETERS, ChunkingParameters);
  }
  #[inline]
  pub fn add_ChunkLookup(&mut self, ChunkLookup: ::flatbuffers::WIPOffset<ReleaseManifestChunkLookup<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestChunkLookup>>(ReleaseManifestBody::VT_CHUNKLOOKUP, ChunkLookup);
  }
  #[inline]
  pub fn add_BundleLookup(&mut self, BundleLookup: ::flatbuffers::WIPOffset<ReleaseManifestLookup<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestLookup>>(ReleaseManifestBody::VT_BUNDLELOOKUP, BundleLookup);
  }
  #[inline]
  pub fn add_FileLookup(&mut self, FileLookup: ::flatbuffers::WIPOffset<ReleaseManifestLookup<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestLookup>>(ReleaseManifestBody::VT_FILELOOKUP, FileLookup);
  }
  #[inline]
  pub fn add_DirectoryLookup(&mut self, DirectoryLookup: ::flatbuffers::WIPOffset<ReleaseManifestLookup<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ReleaseManifestLookup>>(ReleaseManifestBody::VT_DIRECTORYLOOKUP, DirectoryLookup);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReleaseManifestBodyBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReleaseManifestBodyBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReleaseManifestBody<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReleaseManifestBody<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReleaseManifestBody");
      ds.field("Bundles", &self.Bundles());
      ds.field("Languages", &self.Languages());
      ds.field("Files", &self.Files());
      ds.field("Directories", &self.Directories());
      ds.field("EncryptionKeys", &self.EncryptionKeys());
      ds.field("ChunkingParameters", &self.ChunkingParameters());
      ds.field("ChunkLookup", &self.ChunkLookup());
      ds.field("BundleLookup", &self.BundleLookup());
      ds.field("FileLookup", &self.FileLookup());
      ds.field("DirectoryLookup", &self.DirectoryLookup());
      ds.finish()
  }
}
}  // pub mod ReleaseManifestFile
}  // pub mod IO
}  // pub mod LeagueToolkit

