//! RMAN manifests (`docs/SOURCES.md`, "RMAN manifests"): a 28-byte header, then a zstd-compressed
//! flatbuffer body whose XXH64 is the manifest's id. The schema is `rman/` beside this crate; the
//! reader generated from it is `generated.rs`.
//!
//! What is kept: the chunking parameters, each file with its path, tags and chunk ids, and each
//! chunk's place in its bundle, which describes this manifest's bundles and no other.

#[allow(warnings, clippy::all, reason = "generated by flatc from rman/*.fbs")]
mod generated;

use std::collections::HashMap;

use camino::Utf8Path;
use xxhash_rust::xxh64::xxh64;

use generated::league_toolkit::io::release_manifest_file as fb;

use crate::chunk_hash::ChunkHash;
use crate::Error;

const HEADER_LEN: usize = 28;

/// One chunking parameter set; its version selects the chunk hash.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ChunkingParams {
    pub id: u16,
    pub version: u8,
}

/// Where a chunk is in this manifest's bundles.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BundleChunk {
    pub bundle: u64,
    /// The sum of the compressed sizes of the chunks before it in its bundle.
    pub offset: u64,
    pub compressed_size: u32,
    pub uncompressed_size: u32,
}

/// One chunk of a file: its id, the hash its id is under, and where it is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ChunkRef {
    pub id: u64,
    pub hash: ChunkHash,
    pub place: BundleChunk,
}

/// One file of a manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestFile {
    /// The manifest's id for this version of the file.
    pub id: u64,
    /// Its directories and name joined with `/`, as the manifest spells them.
    pub path: String,
    pub size: u64,
    /// The names of its tags, in tag id order; empty for a file with none.
    pub tags: Vec<String>,
    pub params_id: u16,
    /// In file order.
    pub chunk_ids: Vec<u64>,
}

/// A manifest's files and its bundles' layout.
#[derive(Debug)]
pub struct Manifest {
    /// XXH64 of the decompressed body.
    pub id: u64,
    pub params: Vec<ChunkingParams>,
    pub files: Vec<ManifestFile>,
    chunks: HashMap<u64, BundleChunk>,
}

impl Manifest {
    /// A manifest file on disk.
    pub fn read(path: &Utf8Path) -> Result<Self, Error> {
        Self::parse(&fs_err::read(path)?).map_err(|e| match e {
            Error::Manifest(message) => Error::Manifest(format!("{path}: {message}")),
            e => e,
        })
    }

    /// A manifest's bytes: the header and the body, checked against the id the header gives.
    pub fn parse(bytes: &[u8]) -> Result<Self, Error> {
        let fail = |message: String| Error::Manifest(message);
        let header = bytes.get(..HEADER_LEN).ok_or_else(|| fail("shorter than a header".into()))?;
        if &header[..4] != b"RMAN" || header[4] != 2 {
            return Err(fail(format!("not an RMAN manifest of major version 2: {:02x?}", &header[..5])));
        }
        let u32_at = |at: usize| u32::from_le_bytes(header[at..at + 4].try_into().expect("four bytes"));
        let (offset, compressed, length) = (u32_at(8) as usize, u32_at(12) as usize, u32_at(24) as usize);
        let id = u64::from_le_bytes(header[16..24].try_into().expect("eight bytes"));
        let body = offset
            .checked_add(compressed)
            .and_then(|end| bytes.get(offset..end))
            .ok_or_else(|| fail("the body runs past the end".into()))?;
        let body = zstd::bulk::decompress(body, length).map_err(|e| fail(format!("the body: {e}")))?;
        if body.len() != length {
            return Err(fail(format!("the body is {} bytes, the header says {length}", body.len())));
        }
        let actual = xxh64(&body, 0);
        if actual != id {
            return Err(fail(format!("the header's id is {id:016x}, the body hashes to {actual:016x}")));
        }
        let opts = flatbuffers::VerifierOptions {
            // Every bundle chunk is a table, and the lookup tables hold them again.
            max_tables: 1 << 26,
            max_apparent_size: 1 << 31,
            ..Default::default()
        };
        let root = match flatbuffers::root_with_opts::<fb::ReleaseManifestBody>(&opts, &body) {
            Ok(root) => root,
            // Riot's writer does not align 64-bit fields (a 16.3 manifest has a chunk id four
            // bytes off). The generated reads copy bytes rather than dereference, so the walk is
            // safe without the verifier's alignment check.
            Err(flatbuffers::InvalidFlatbuffer::Unaligned { .. }) => {
                // SAFETY: the body hashed to the manifest's id, so it is Riot's own; the only
                // verifier failure is alignment, which byte-copying reads do not need.
                unsafe { flatbuffers::root_unchecked::<fb::ReleaseManifestBody>(&body) }
            }
            Err(e) => return Err(fail(format!("the body: {e}"))),
        };
        Self::walk(id, root)
    }

    fn walk(id: u64, root: fb::ReleaseManifestBody<'_>) -> Result<Self, Error> {
        let fail = |message: String| Error::Manifest(message);
        let tags: HashMap<u8, &str> = root.Languages().into_iter().flatten().map(|t| (t.ID(), t.Name().unwrap_or_default())).collect();
        let dirs: HashMap<u64, (u64, &str)> =
            root.Directories().into_iter().flatten().map(|d| (d.ID(), (d.ParentID(), d.Name().unwrap_or_default()))).collect();
        let params: Vec<ChunkingParams> =
            root.ChunkingParameters().into_iter().flatten().map(|p| ChunkingParams { id: p.ID(), version: p.Version() }).collect();

        let mut chunks = HashMap::new();
        for bundle in root.Bundles().into_iter().flatten() {
            let mut offset = 0u64;
            for chunk in bundle.Chunks().into_iter().flatten() {
                let place = BundleChunk {
                    bundle: bundle.ID(),
                    offset,
                    compressed_size: chunk.CompressedSize(),
                    uncompressed_size: chunk.UncompressedSize(),
                };
                // A chunk two bundles hold keeps its first place.
                chunks.entry(chunk.ID()).or_insert(place);
                offset += u64::from(chunk.CompressedSize());
            }
        }

        let mut files = Vec::new();
        for file in root.Files().into_iter().flatten() {
            let id = file.ID();
            let mut path = file.Name().unwrap_or_default().to_string();
            let mut dir = file.DirectoryID();
            for _ in 0..=64 {
                if dir == 0 {
                    break;
                }
                let (parent, name) = dirs.get(&dir).ok_or_else(|| fail(format!("file {id:016x} is in unknown directory {dir}")))?;
                if !name.is_empty() {
                    path = format!("{name}/{path}");
                }
                dir = *parent;
            }
            if dir != 0 {
                return Err(fail(format!("file {id:016x}: a directory cycle")));
            }
            let mask = file.TagBitmask();
            let tags = (0..64u8)
                .filter(|bit| mask & (1u64 << bit) != 0)
                .map(|bit| tags.get(&(bit + 1)).map(|t| t.to_string()).ok_or_else(|| fail(format!("file {id:016x} has unknown tag {}", bit + 1))))
                .collect::<Result<Vec<_>, _>>()?;
            let params_id = file.ChunkingParametersID();
            if !params.iter().any(|p| p.id == params_id) {
                return Err(fail(format!("file {id:016x} uses unknown chunking parameters {params_id}")));
            }
            let chunk_ids: Vec<u64> = file.ChunkIDs().map(|v| v.iter().collect()).unwrap_or_default();
            let mut total = 0u64;
            for chunk in &chunk_ids {
                let place = chunks.get(chunk).ok_or_else(|| fail(format!("file {id:016x} has unknown chunk {chunk:016x}")))?;
                total += u64::from(place.uncompressed_size);
            }
            if total != file.Size() {
                return Err(fail(format!("file {id:016x} is {} bytes, its chunks {total}", file.Size())));
            }
            files.push(ManifestFile { id, path, size: file.Size(), tags, params_id, chunk_ids });
        }
        Ok(Self { id, params, files, chunks })
    }

    /// A manifest made in code. Every chunk of every file has a place in `chunks`.
    pub fn new(id: u64, params: Vec<ChunkingParams>, files: Vec<ManifestFile>, chunks: HashMap<u64, BundleChunk>) -> Self {
        Self { id, params, files, chunks }
    }

    /// Where a chunk is in this manifest's bundles.
    pub fn place(&self, chunk_id: u64) -> Option<BundleChunk> {
        self.chunks.get(&chunk_id).copied()
    }

    /// A file's chunks, in file order.
    pub fn chunks_of(&self, file: &ManifestFile) -> Result<Vec<ChunkRef>, Error> {
        let version = self.params.iter().find(|p| p.id == file.params_id).map(|p| p.version);
        let hash = version.and_then(ChunkHash::from_version).ok_or_else(|| {
            Error::Manifest(format!("file {:016x}: chunking parameters of version {version:?}", file.id))
        })?;
        Ok(file
            .chunk_ids
            .iter()
            .map(|&id| ChunkRef { id, hash, place: self.chunks[&id] })
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use flatbuffers::FlatBufferBuilder;

    use super::*;

    /// A manifest of one file in two chunks, each in its own bundle after another chunk, built
    /// with the generated builder (which is why this test is here and not in `tests/`).
    fn manifest() -> Vec<u8> {
        let mut b = FlatBufferBuilder::new();
        let mut bundles = Vec::new();
        for (bundle, chunks) in [(0x77, [(0x1, 7, 70), (0xA, 5, 10)]), (0x78, [(0x2, 9, 90), (0xB, 6, 20)])] {
            let chunks: Vec<_> = chunks
                .iter()
                .map(|&(id, c, u)| {
                    let args = fb::ReleaseManifestBundleChunkArgs { ID: id, CompressedSize: c, UncompressedSize: u };
                    fb::ReleaseManifestBundleChunk::create(&mut b, &args)
                })
                .collect();
            let chunks = b.create_vector(&chunks);
            bundles.push(fb::ReleaseManifestBundle::create(&mut b, &fb::ReleaseManifestBundleArgs { ID: bundle, Chunks: Some(chunks) }));
        }
        let bundles = b.create_vector(&bundles);
        let names = [b.create_string("en_US"), b.create_string("ko_KR")];
        let tags: Vec<_> = names
            .iter()
            .zip([1, 3])
            .map(|(&name, id)| fb::ReleaseManifestLanguage::create(&mut b, &fb::ReleaseManifestLanguageArgs { ID: id, Name: Some(name) }))
            .collect();
        let tags = b.create_vector(&tags);
        let (data, final_) = (b.create_string("DATA"), b.create_string("FINAL"));
        let dirs = [(1, 0, data), (2, 1, final_)].map(|(id, parent, name)| {
            fb::ReleaseManifestDirectory::create(&mut b, &fb::ReleaseManifestDirectoryArgs { ID: id, ParentID: parent, Name: Some(name) })
        });
        let dirs = b.create_vector(&dirs);
        let params = fb::ReleaseManifestChunkingParameter::create(
            &mut b,
            &fb::ReleaseManifestChunkingParameterArgs { ID: 3, Version: 4, MinChunkSize: 16384, TargetChunkSize: 65536, MaxChunkSize: 8388608 },
        );
        let params = b.create_vector(&[params]);
        let name = b.create_string("Ahri.wad.client");
        let ids = b.create_vector(&[0xAu64, 0xB]);
        let file = fb::ReleaseManifestFile::create(
            &mut b,
            &fb::ReleaseManifestFileArgs {
                ID: 0xF1,
                DirectoryID: 2,
                Size: 30,
                Name: Some(name),
                TagBitmask: 0b101,
                ChunkIDs: Some(ids),
                ChunkingParametersID: 3,
                ..Default::default()
            },
        );
        let files = b.create_vector(&[file]);
        let body = fb::ReleaseManifestBody::create(
            &mut b,
            &fb::ReleaseManifestBodyArgs {
                Bundles: Some(bundles),
                Languages: Some(tags),
                Files: Some(files),
                Directories: Some(dirs),
                ChunkingParameters: Some(params),
                ..Default::default()
            },
        );
        b.finish(body, None);
        let body = b.finished_data();
        let compressed = zstd::bulk::compress(body, 3).unwrap();
        let mut bytes = b"RMAN\x02\x01\x00\x00".to_vec();
        bytes.extend((HEADER_LEN as u32).to_le_bytes());
        bytes.extend((compressed.len() as u32).to_le_bytes());
        bytes.extend(xxh64(body, 0).to_le_bytes());
        bytes.extend((body.len() as u32).to_le_bytes());
        bytes.extend(compressed);
        bytes
    }

    #[test]
    fn reads_files_tags_and_each_chunks_place_in_its_bundle() {
        let manifest = Manifest::parse(&manifest()).unwrap();
        let file = &manifest.files[0];
        assert_eq!((file.id, file.path.as_str(), file.size), (0xF1, "DATA/FINAL/Ahri.wad.client", 30));
        assert_eq!(file.tags, ["en_US", "ko_KR"]);
        let chunks = manifest.chunks_of(file).unwrap();
        assert_eq!(chunks.len(), 2);
        assert_eq!(chunks[0], ChunkRef { id: 0xA, hash: ChunkHash::Blake3, place: BundleChunk { bundle: 0x77, offset: 7, compressed_size: 5, uncompressed_size: 10 } });
        assert_eq!(chunks[1].place, BundleChunk { bundle: 0x78, offset: 9, compressed_size: 6, uncompressed_size: 20 });
    }

    #[test]
    fn rejects_a_body_that_does_not_hash_to_the_id() {
        let mut bytes = manifest();
        bytes[16] ^= 1;
        assert!(matches!(Manifest::parse(&bytes), Err(Error::Manifest(m)) if m.contains("hashes to")));
        assert!(Manifest::parse(&bytes[..20]).is_err());
    }
}
